import type { Metadata } from "next";
import PageHero from "@/components/portal/PageHero";
import CtaBreak from "@/components/portal/CtaBreak";

export const metadata: Metadata = {
  title: "Solar Battery Storage | Enphase IQ Battery | Solar Command",
  description:
    "Power your Maryland home day and night with Enphase IQ battery storage. Store excess solar energy, protect against outages, and save money.",
};

export default function BatteriesPage() {
  return (
    <div>
      {/* ── Hero ──────────────────────────────────────────────── */}
      <PageHero
        title="Solar Battery Storage"
        subtitle="Power Your Home Day and Night"
        description="Store excess solar energy for nighttime use, cloudy days, and power outages. A quality solar PV system with battery backup reduces your electric bill by 50 to 90 percent."
      />

      {/* ── 1. What Are Solar Batteries ───────────────────────── */}
      <section className="py-16 sm:py-20">
        <div className="mx-auto max-w-5xl px-4 sm:px-6">
          <h2 className="text-center text-3xl font-bold text-amber-600">
            What Are Solar Batteries?
          </h2>
          <div className="mx-auto mt-6 max-w-3xl space-y-4 text-solar-700 leading-relaxed">
            <p>
              Solar batteries store excess energy generated by your solar panels
              during the day so you can use it when you need it most — at night,
              on cloudy days, and during power outages. Instead of sending unused
              electricity back to the grid, a battery system captures that energy
              and keeps it ready for your home.
            </p>
            <p>
              When paired with a solar PV system, batteries give you true energy
              independence. Your panels generate electricity during peak sunlight
              hours, the battery stores what you don&apos;t use immediately, and
              your home draws from that stored energy after the sun goes down.
              This means you rely less on the utility grid and more on your own
              clean power.
            </p>
            <p>
              Modern battery systems include app-based monitoring so you can
              track your energy production, storage levels, and household
              consumption in real time from your smartphone. You always know
              exactly how much power you have stored and how your system is
              performing — giving you complete visibility and control over your
              home energy.
            </p>
          </div>
        </div>
      </section>

      {/* ── 2. Enphase IQ Battery ─────────────────────────────── */}
      <section className="bg-white border-t border-gray-100 py-16 sm:py-20">
        <div className="mx-auto max-w-5xl px-4 sm:px-6">
          <h2 className="text-center text-3xl font-bold text-amber-600">
            Why We Recommend the Enphase IQ Battery
          </h2>
          <p className="mt-2 text-center text-solar-700">
            Industry-leading technology backed by a comprehensive warranty
          </p>
          <div className="mt-10 grid gap-8 sm:grid-cols-3">
            {/* Enhanced Power Output */}
            <div className="rounded-xl bg-white p-6 text-center shadow-sm border border-gray-200">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-solar-100 text-solar-600">
                <svg
                  width={28}
                  height={28}
                  className="h-7 w-7"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z"
                  />
                </svg>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Enhanced Power Output
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                Run high-demand appliances like AC units and refrigerators even
                during outages.
              </p>
            </div>

            {/* High Storage Capacity */}
            <div className="rounded-xl bg-white p-6 text-center shadow-sm border border-gray-200">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-sunburst-100 text-sunburst-600">
                <svg
                  width={28}
                  height={28}
                  className="h-7 w-7"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 10.5h.375c.621 0 1.125.504 1.125 1.125v2.25c0 .621-.504 1.125-1.125 1.125H21M3.75 18h15A2.25 2.25 0 0021 15.75v-6a2.25 2.25 0 00-2.25-2.25h-15A2.25 2.25 0 001.5 9.75v6A2.25 2.25 0 003.75 18z"
                  />
                </svg>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                High Storage Capacity
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                Power major home appliances for hours during grid failures.
                Enough capacity for your essential needs.
              </p>
            </div>

            {/* Mobile App Monitoring */}
            <div className="rounded-xl bg-white p-6 text-center shadow-sm border border-gray-200">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-purple-100 text-purple-600">
                <svg
                  width={28}
                  height={28}
                  className="h-7 w-7"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M10.5 1.5H8.25A2.25 2.25 0 006 3.75v16.5a2.25 2.25 0 002.25 2.25h7.5A2.25 2.25 0 0018 20.25V3.75a2.25 2.25 0 00-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3"
                  />
                </svg>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Mobile App Monitoring
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                Track your energy production, storage levels, and consumption in
                real-time from your phone.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── 3. Benefits of Solar Battery Storage ──────────────── */}
      <section className="py-16 sm:py-20">
        <div className="mx-auto max-w-5xl px-4 sm:px-6">
          <h2 className="text-center text-3xl font-bold text-amber-600">
            Benefits of Solar Battery Storage
          </h2>
          <div className="mt-10 grid gap-8 sm:grid-cols-3">
            {/* Energy Independence */}
            <div className="flex flex-col items-center text-center">
              <div className="flex h-14 w-14 items-center justify-center rounded-full bg-solar-100 text-solar-600">
                <svg
                  width={28}
                  height={28}
                  className="h-7 w-7"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M2.25 21h19.5m-18-18v18m10.5-18v18m6-13.5V21M6.75 6.75h.75m-.75 3h.75m-.75 3h.75m3-6h.75m-.75 3h.75m-.75 3h.75M6.75 21v-3.375c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21M3 3h12m-.75 4.5H21m-3.75 3H21m-3.75 3H21"
                  />
                </svg>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Energy Independence
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                Backup power when sunlight or grid access is unavailable. Never
                worry about blackouts again.
              </p>
            </div>

            {/* Financial Savings */}
            <div className="flex flex-col items-center text-center">
              <div className="flex h-14 w-14 items-center justify-center rounded-full bg-green-100 text-green-600">
                <svg
                  width={28}
                  height={28}
                  className="h-7 w-7"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Financial Savings
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                Use stored energy during peak utility rate hours to reduce your
                electricity costs. Avoid expensive time-of-use charges.
              </p>
            </div>

            {/* Environmental Impact */}
            <div className="flex flex-col items-center text-center">
              <div className="flex h-14 w-14 items-center justify-center rounded-full bg-sunburst-100 text-sunburst-600">
                <svg
                  width={28}
                  height={28}
                  className="h-7 w-7"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12.75 3.03v.568c0 .334.148.65.405.864l1.068.89c.442.369.535 1.01.216 1.49l-.51.766a2.25 2.25 0 01-1.161.886l-.143.048a1.107 1.107 0 00-.57 1.664c.369.555.169 1.307-.427 1.592L9 13.125l.423 1.059a.956.956 0 01-1.652.928l-.679-.906a1.125 1.125 0 00-1.906.172L4.5 15.75l-.612.153M12.75 3.031a9 9 0 00-8.862 12.872M12.75 3.031a9 9 0 016.69 14.036m0 0l-.177-.529A2.25 2.25 0 0017.128 15H16.5l-.324-.324a1.453 1.453 0 00-2.328.377l-.036.073a1.586 1.586 0 01-.982.816l-.99.282c-.55.157-.894.702-.8 1.267l.073.438c.08.474.49.821.97.821.846 0 1.598.542 1.865 1.345l.215.643m5.276-3.67a9.012 9.012 0 01-5.276 3.67"
                  />
                </svg>
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Environmental Impact
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                Increase your use of clean, renewable energy and reduce reliance
                on fossil-fuel-powered grid electricity.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── 4. 30% Tax Credit Callout ─────────────────────────── */}
      <section className="py-4 sm:py-6">
        <div className="mx-auto max-w-5xl px-4 sm:px-6">
          <div className="rounded-2xl bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 p-8 sm:p-12 text-center">
            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-solar-500/20">
              <svg
                width={32}
                height={32}
                className="h-8 w-8 text-solar-400"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <h2 className="mt-6 text-2xl font-bold text-white sm:text-3xl">
              Save 30% with the Federal Tax Credit
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-gray-300 leading-relaxed">
              Solar batteries are eligible for the 30% federal tax credit, just
              like your solar panels. Battery systems can also be added to
              existing solar installations — so even if you already have panels
              on your roof, you can still take advantage of this significant
              savings when you add battery storage.
            </p>
            <div className="mt-6 inline-flex items-center gap-2 rounded-full bg-solar-500/20 px-5 py-2 text-sm font-medium text-solar-300">
              <svg
                width={16}
                height={16}
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={2}
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              Available through 2032
            </div>
          </div>
        </div>
      </section>

      {/* ── 5. 3-Step Installation Process ────────────────────── */}
      <section className="bg-white border-t border-gray-100 py-16 sm:py-20">
        <div className="mx-auto max-w-5xl px-4 sm:px-6">
          <h2 className="text-center text-3xl font-bold text-amber-600">
            How Do I Get Solar Batteries Installed?
          </h2>
          <p className="mt-2 text-center text-solar-700">
            Three simple steps to energy independence
          </p>
          <div className="mt-12 grid gap-8 sm:grid-cols-3">
            {/* Step 1 */}
            <div className="flex flex-col items-center text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-solar-600 text-lg font-bold text-white">
                1
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Free Energy Assessment
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                We evaluate your energy storage needs based on your home size,
                usage patterns, and backup requirements.
              </p>
            </div>

            {/* Step 2 */}
            <div className="flex flex-col items-center text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-solar-600 text-lg font-bold text-white">
                2
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Customized Recommendation
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                We recommend the right battery configuration for your home,
                including capacity and number of units.
              </p>
            </div>

            {/* Step 3 */}
            <div className="flex flex-col items-center text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-solar-600 text-lg font-bold text-white">
                3
              </div>
              <h3 className="mt-4 text-lg font-semibold text-amber-600">
                Expert Installation
              </h3>
              <p className="mt-2 text-sm text-solar-700 leading-relaxed">
                Our factory-trained technicians seamlessly integrate the battery
                with your solar system.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── CTA Break ─────────────────────────────────────────── */}
      <CtaBreak
        heading="Ready for Energy Independence?"
        subtext="Add battery backup to your solar system and never worry about power outages again."
      />
    </div>
  );
}
